### ISSUE TITLE
recon_vis speciation renders too far from host node

### ISSUE THREAD

**Issue by justinjiang1212** [ssantichaivekin/empress#155]
When there are multiple events on one host node and the speciation is the last event to be rendered, the speciation gets rendered very far away from the host node. Below, the two black circles are examples of this issue.
![Figure_1](https://user-images.githubusercontent.com/61333589/87849173-559c1580-c89b-11ea-90ed-644d0928d0a7.png)

**Comment by ssantichaivekin** [comment]
Thank you for opening this issue! 👍 This is really appreciated! 🥇 

Here are some very minor comments: I think one issue should be used to comment on one thing. It would be nice if you remove the "The confusing duplications has been fixed, if you compare the root of the parasite tree of the above example to the below example" to the pull request comment. It would be nice to copy both images to that pull request comment. You could resolve the second image from this issue.

For the transfer sliding feature "Since transfer sliding is more of a "feature" to be implemented instead of a bug on our end, I'm not going to describe it in detail in this open issue" please remove it from here and open a new issue for it. It's okay to use issue for feature requests. You don't have to describe the feature in detail, but you can if you want to. 😄

**Comment by justinjiang1212** [comment]
Will do!
