### ISSUE TITLE
recon_vis sliding transfer feature

### ISSUE THREAD

**Issue by justinjiang1212** [ssantichaivekin/empress#157]
Sometimes, a diagonal transfer can be forced to "slide" down the host edge so that the transfer becomes temporally consistent.

**Comment by ssantichaivekin** [comment]
Could you also add an example of transfers that could be slide down the host edge? Thank you! :)

**Comment by justinjiang1212** [comment]
![Screen Shot 2020-07-20 at 3 33 58 PM](https://user-images.githubusercontent.com/61333589/87993097-8c8e4900-ca9e-11ea-941e-da777ffa8263.png)
The circled node can be slid all the way down the host edge to make a vertical transfer.

**Comment by ssantichaivekin** [comment]
This is a very nice example 😀

**Comment by TrentonJW** [comment]
I believe this issue is fixed.
Here is a picture of a tree before adding the slide transfer feature.
![Figure_1](https://user-images.githubusercontent.com/65570452/88112174-e8c39c80-cb74-11ea-87c1-716c5a9954e7.png)
And here is the same tree after added the feature
![Figure_1](https://user-images.githubusercontent.com/65570452/88112205-faa53f80-cb74-11ea-9b15-09b898887d64.png)
