### ISSUE TITLE
GUI: Number of clusters and old cluster data not removed when changing cost

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#182]
**Problem:**

The number of clusters is not updated when using `Set the number of clusters` after changing the cost of duplication/transfer/loss. The previous clustering data also remains available after changing the cost. Clicking on it displays the old clustering data.

<img width="957" alt="Screen Shot 2020-07-23 at 8 52 02 PM" src="https://user-images.githubusercontent.com/19219105/88361439-c88b0d80-cd2d-11ea-84d1-bd0e66325b6b.png">

**Steps to reproduce:**

1. Load gopher-louse data from examples.

2. Click `Compute Reconciliations` without changing the costs (it's 1,1,1). The number of MPRs is two.

3. Click `View solution space` -> `Clusters`. Enter 1.
<img width="400" alt="Screen Shot 2020-07-23 at 9 55 17 PM" src="https://user-images.githubusercontent.com/19219105/88361827-3a178b80-cd2f-11ea-98b2-65193c6f4f22.png">

4. Click `View reconciliations` -> `One per cluster`. It shows one reconciliation drawing. Nothing is wrong so far.
<img width="400" alt="Screen Shot 2020-07-23 at 9 55 41 PM" src="https://user-images.githubusercontent.com/19219105/88361840-47347a80-cd2f-11ea-9376-eb37372ecce9.png">

5. Change duplication cost to 2 and transfer cost to 4, then click compute reconciliations. There are 2 MPRs.

6. Click `View solution space` -> `Clusters`. Enter 2. It produces incorrect output.
<img width="957" alt="Screen Shot 2020-07-23 at 8 52 02 PM" src="https://user-images.githubusercontent.com/19219105/88361439-c88b0d80-cd2d-11ea-84d1-bd0e66325b6b.png">

7. Click `View reconciliations` -> `One per cluster` shows the old reconciliation.
<img width="400" alt="Screen Shot 2020-07-23 at 10 05 29 PM" src="https://user-images.githubusercontent.com/19219105/88362259-ae066380-cd30-11ea-8782-e1013aa02ff4.png">

**Comment by Qing-Yang-1211** [comment]
I couldn't reproduce the bug because at step 5 (Change duplication cost to 2 and transfer cost to 4, then click compute reconciliations. There are 2 MPRs.), there were actually 6 MPRs instead of 2. And at step 6 (Click `View solution space` -> `Clusters`. Enter 2. It produces incorrect output.), it actually gave the correct output. 
However, I did found an issue with the variable self.num_cluster. That is, when I entered 2 at step 3 and 2 again at step 6 without editing the entry field at step 6, I got the error described in this issue. I have fixed this in pull request #183. 
After fixing it, I found a new bug.
Steps to reproduce the bug (using the branch gui-fix-num-cluster-bug):
1. Load gopher-louse data from examples.
2. Click Compute Reconciliations without changing the costs (it's 1,1,1). The number of MPRs is 2.
3. Click View solution space -> Clusters. Enter 2.
4. Click `View reconciliations` -> `One per cluster`. It shows two reconciliation drawings. Nothing is wrong so far.
<img width="829" alt="Screen Shot 2020-07-24 at 10 30 03 PM" src="https://user-images.githubusercontent.com/54883284/88402131-4407c000-cdfd-11ea-885a-d1d4c031b303.png">
5. Change duplication cost to 2 and transfer cost to 4, then click compute reconciliations. There are 6 MPRs. 
6. Click `View solution space` -> `Clusters`. Enter 2 (no need to edit the entry field). Nothing is wrong so far.
7. Click `View reconciliations` -> `One per cluster` shows the bug.
<img width="947" alt="Screen Shot 2020-07-24 at 10 34 36 PM" src="https://user-images.githubusercontent.com/54883284/88402602-f2136a00-cdfd-11ea-8065-d08ffc5d5caa.png">
<img width="940" alt="Screen Shot 2020-07-24 at 10 35 04 PM" src="https://user-images.githubusercontent.com/54883284/88402606-f3449700-cdfd-11ea-9f95-c79d1296dc48.png">

**Comment by ssantichaivekin** [comment]
This seems to be related with the original bug. It seems like clicking `Enter` in `View solution space` -> `Clusters` sometimes does not update the saved clusters.

**Comment by ssantichaivekin** [comment]
Solved because #219 is merged into master indirectly via #218. Note that we should have merged #218 into master first and then merge #219 into master later so that there are two commits on master. But the way we merge makes it such that there's only one commit for #218 in master which also contains the changes for #219.
