### ISSUE TITLE
Cannot export reconciliation images as pdf

### ISSUE THREAD

**Issue by Jorge-Dona** [ssantichaivekin/empress#229]
Hi,

I'm trying to save a figure in a vectorial format (e.g., PDF).  However, I'm only allowed to save figures in PNG.  I'm running eMPRess on a Mac and installed it following the instructions from the eMPRess website –other than this is running with no issues.

<img width="2075" alt="Screen Shot 2021-06-02 at 9 11 46 AM" src="https://user-images.githubusercontent.com/9450421/120495757-9bae7a80-c382-11eb-9ed5-db8044b942d7.png">

Thanks!

Jorge

**Comment by ssantichaivekin** [comment]
Hi Jorge,

Thank you for using eMPRess!

It seems like my save dialogue box looks different from yours. This might be due to the macOS version. Here's what the save dialogue box looks like for me:

<img width="843" alt="Screen Shot 2021-06-02 at 10 06 23 PM" src="https://user-images.githubusercontent.com/19219105/120504990-c7ffe080-c3ee-11eb-975c-b096c643a700.png">

My eMPRess doesn't show the format of the file being saved. However, if I change the filename to `image.pdf` the image saves correctly. Could you try that and see how it goes?

**Comment by Jorge-Dona** [comment]
Hi Santi.

I tried that already and it didn't work.  When I do that I get this:

![image](https://user-images.githubusercontent.com/9450421/120533703-a4b14300-c3a6-11eb-82e4-c1660e45d970.png)

Then, I've tried both the "use .png" option and "use both" and in both cases, the saved figure is a .png file. My macOS version is 11.2.3 Big Sur.

Thanks!

Jorge

**Comment by ssantichaivekin** [comment]
I will try to work on some fixes, but I don't have a Big Sur machine so it might take a while. Meanwhile, you can send me the files at jsantichaivekin@g.hmc.edu and I will send back the pdf.

**Comment by ssantichaivekin** [comment]
Could you try using [this version of eMPRess](https://github.com/ssantichaivekin/empress/suites/2898651901/artifacts/64949852) instead and see how it goes?

**Comment by Jorge-Dona** [comment]
Hi Santi,

It worked.  I installed it using the command line.

Thanks!

Jorge

**Comment by ssantichaivekin** [comment]
No problem! A little heads up: that version doesn't work with macOS dark mode. If you switch to dark mode you might see the texts disappearing.

**Comment by ssantichaivekin** [comment]
@Jorge-Dona Another quick question, does the macOS executable on the download page works? It works on my computer (macOS Catalina 10.15.7) but I haven't tested it on Big Sur.

**Comment by ssantichaivekin** [comment]
It seems like the problem is caused by newer versions of tk shipped with python.org and anaconda's python distribution and only occur in macOS.
- Installing python 3.7 with homebrew `brew install python@3.7` instead of using python.org or anaconda's distribution fixes the issue. Homebrew python distribution does not ship with tk so the app defaults to an older version of tk that ships with macOS.
-  The executable from the download page uses Github's python distribution which also does not ship with tk. This means it should also be able to save images as pdf.
- This issue might occur in all matplotlib plots. I will investigate this issue further and report to matplotlib if this is the case.

**Comment by Jorge-Dona** [comment]
> @Jorge-Dona Another quick question, does the macOS executable on the download page works? It works on my computer (macOS Catalina 10.15.7) but I haven't tested it on Big Sur.

Hi, Santi.  It didn't work for me.
